"""Persistent SBCL worker pool over a stdio s-expression protocol.

Issues.md #3 (pool is not persistent), #27 (no reset protocol), #28
(no health model). Where :func:`workers.run_lisp` spawns a fresh SBCL
per job, :class:`Pool` keeps ``size`` long-lived SBCL subprocesses and
drives each over a one-line-at-a-time ASCII protocol on stdio::

    pool -> worker   JOB <job-id> <prelude-b64|-> <code-b64>
    worker -> pool   RESULT <job-id> <json>
    pool -> worker   PING                  worker -> pool   PONG <worker-id>
    pool -> worker   RESET                 worker -> pool   RESET-OK sandbox=<yes|no>
                                                      (or RESET-FAIL <msg>)
    pool -> worker   BYE                   (worker exits 0)

Code travels base64 (UTF-8 inside) so the pipe never depends on locale
external-formats; results are ASCII-only JSON (``\\u``-escaped, same
shape as :func:`workers.run_lisp` plus ``worker_id``/``job_id``/
``generation``). The worker prints ``READY <worker-id>`` after boot;
anything before it is startup noise and is skipped.

Health, poison, recycle, reset, generation ownership:

* health: checkout-time liveness + ``PING`` when idle too long or every
  N jobs; failures destroy and replace the worker,
* poison: EOF, malformed ``RESULT`` (bad job id / bad JSON), timeout,
  or generation mismatch destroys the worker immediately — a wedged
  eval cannot be interrupted over stdio, so timeouts always kill,
* recycle: a worker is destroyed after ``max_jobs_per_worker`` jobs or
  ``max_age_s`` seconds (bounded lifetimes),
* reset: ``RESET`` deletes and recreates the per-job package (best
  effort — code that leaves the job package escapes it) and reports
  the sandbox state; hard recycle stays the real hygiene,
* generation: every worker is stamped with the pool generation
  (default: :func:`fingerprint.compute_string`); each ``RESULT`` echoes
  it and mismatches poison the worker; :meth:`Pool.regenerate`
  destroys the fleet for epoch changes.

Fallback: when a persistent worker cannot serve a job (spawn failure,
poison) and ``oneshot_fallback`` is true (default), that job is
delegated to :func:`workers.run_lisp` for a one-shot run. This is the
only sanctioned call into the sibling-owned :mod:`workers` module, and
it is call-only — this file never edits it.

Secret hygiene: spawned workers get a scrubbed environment
(:func:`_scrub_env` removes ``CEREBRAS_API_KEY``/``CEREBRAS``); the
worker script embeds no secrets. See ``documents/secret-policy.md``.

Stdlib plus optional repo siblings (``sandbox`` for the boot prelude,
``fingerprint`` for the default generation, ``workers`` for one-shot
fallback) — every sibling import degrades gracefully when absent.
"""

from __future__ import annotations

import base64
import collections
import hashlib
import json
import os
import queue
import subprocess
import tempfile
import threading
import time
import uuid

try:
    import sandbox as _sandbox
except ImportError:
    _sandbox = None

try:
    import fingerprint as _fingerprint
except ImportError:
    _fingerprint = None

try:
    import workers as _workers
except ImportError:
    _workers = None

__all__ = [
    "Pool",
    "PersistentWorker",
    "WorkerError",
    "WorkerSpawnError",
    "WorkerPoisonedError",
    "TargetFrozenError",
    "RESULT_KEYS",
    "DEFAULT_MAX_JOBS_PER_WORKER",
    "DEFAULT_MAX_AGE_S",
]

#: Envelope keys every run returns (the six :func:`workers.run_lisp`
#: keys plus pool provenance).
RESULT_KEYS = frozenset({
    "ok", "stdout", "return_value", "error", "timed_out", "elapsed_ms",
    "worker_id", "job_id", "pooled", "generation_ok",
})

#: Conservative bounded-lifetime defaults (short enough to matter on
#: Windows SBCL, long enough to amortize the ~1s spawn).
DEFAULT_MAX_JOBS_PER_WORKER = 100
DEFAULT_MAX_AGE_S = 1800.0

#: Oversized-line tripwire: a RESULT line past this poisons the worker.
MAX_LINE_CHARS = 4 * 1024 * 1024

#: Distinctive secret-bearing variables scrubbed from worker env.
_SCRUB_ENV_VARS = frozenset({"CEREBRAS_API_KEY", "CEREBRAS"})

_EOF = object()

ROOT = os.path.dirname(os.path.abspath(__file__))


class WorkerError(Exception):
    """Base class for pool worker failures."""


class WorkerSpawnError(WorkerError):
    """A persistent worker could not be spawned or readied."""


class WorkerPoisonedError(WorkerError):
    """A worker desynced, timed out, or failed health and was destroyed."""


class TargetFrozenError(WorkerError):
    """Reserved: pool-side refusal hook (storm integration point)."""


# ---------------------------------------------------------------------------
# Worker script (generated temp .lisp executed by each SBCL child)
# ---------------------------------------------------------------------------

_WORKER_SCRIPT = """;;;; GRAYGOO persistent pool worker (generated by pool.py; do not edit).
(defparameter *pool-generation* "@@GENERATION@@")
(defparameter *pool-worker-id* "@@WORKERID@@")
(defparameter *pool-prelude* "@@PRELUDE@@")
(let ((*load-verbose* nil)
      (*load-print* nil)
      (*compile-verbose* nil)
      (*compile-print* nil))
  (load "@@ROOT@@/src/worker/packages.lisp")
  (load "@@ROOT@@/src/worker/worker.lisp")
  (load "@@ROOT@@/src/rehearsal/packages.lisp")
  (load "@@ROOT@@/src/rehearsal/rehearsal.lisp"))
(defun pool-json-escape (string)
  (with-output-to-string (out)
    (loop for ch across string
          for code = (char-code ch)
          do (cond ((char= ch #\\") (write-string "\\\\\\"" out))
                   ((char= ch #\\\\) (write-string "\\\\\\\\" out))
                   ((char= ch #\\Newline) (write-string "\\\\n" out))
                   ((char= ch #\\Return) (write-string "\\\\r" out))
                   ((char= ch #\\Tab) (write-string "\\\\t" out))
                   ((< code 32) (format out "\\\\u~4,'0X" code))
                   ((> code 127)
                    (if (< code 65536)
                        (format out "\\\\u~4,'0X" code)
                        (let ((tail (- code 65536)))
                          (format out "\\\\u~4,'0X\\\\u~4,'0X"
                                  (+ #xD800 (ash tail -10))
                                  (+ #xDC00 (logand tail #x3FF))))))
                   (t (write-char ch out))))))
(defun pool-oneline (string)
  (map 'string (lambda (ch) (if (or (char= ch #\\Newline)
                                      (char= ch #\\Return))
                                 #\\Space ch))
       string))
(defun pool-b64-value (ch)
  (let ((code (char-code ch)))
    (cond ((and (>= code 65) (<= code 90)) (- code 65))
          ((and (>= code 97) (<= code 122)) (+ (- code 97) 26))
          ((and (>= code 48) (<= code 57)) (+ (- code 48) 52))
          ((char= ch #\\+) 62)
          ((char= ch #\\/) 63)
          ((char= ch #\\=) -1)
          (t nil))))
(defun pool-b64-decode (text)
  "Decode base64 TEXT to an octet vector, or NIL on malformed input."
  (when (or (zerop (mod (length text) 4))
            (zerop (length text)))
    (let ((out (make-array 0 :element-type '(unsigned-byte 8)
                             :fill-pointer 0 :adjustable t)))
      (block decode
        (loop for i from 0 below (length text) by 4
              for vals = (mapcar #'pool-b64-value
                                 (list (char text i) (char text (+ i 1))
                                       (char text (+ i 2))
                                       (char text (+ i 3))))
              do (when (some #'null vals) (return-from decode nil))
                 (let ((n (+ (ash (first vals) 18) (ash (second vals) 12)
                             (ash (max (third vals) 0) 6)
                             (max (fourth vals) 0))))
                   (vector-push-extend (ldb (byte 8 16) n) out)
                   (unless (= (third vals) -1)
                     (vector-push-extend (ldb (byte 8 8) n) out))
                   (unless (= (fourth vals) -1)
                     (vector-push-extend (ldb (byte 8 0) n) out)))))
      out)))
(defun pool-decode-text (b64)
  "Decode base64 B64 (UTF-8 inside) to a string, or NIL when malformed."
  (when (string= b64 "-") (return-from pool-decode-text ""))
  (let ((octets (pool-b64-decode b64)))
    (when octets
      (handler-case
          (sb-ext:octets-to-string octets :external-format :utf-8)
        (serious-condition () nil)))))
(defun pool-eval-all (text)
  "Read and EVAL every form in TEXT; return the last value (NIL if none).
Binds *READ-EVAL* to NIL: #.-style reader evaluation never runs in a
pool worker."
  (let ((result nil)
        (*read-eval* nil))
    (with-input-from-string (in text)
      (loop for form = (read in nil in)
            until (eq form in)
            do (setf result (eval form))))
    result))
(defun pool-backtrace ()
  (let ((s (make-string-output-stream)))
    (ignore-errors (sb-debug:print-backtrace :stream s :count 24))
    (get-output-stream-string s)))
(defvar *pool-job-package* nil)
(defun pool-fresh-job-package ()
  (setf *pool-job-package* (make-package :graygoo-job :use '(:cl))))
(pool-fresh-job-package)
(defun pool-sandbox-ok-p ()
  (let* ((pkg (find-package :evo.worker))
         (sym (and pkg (find-symbol "*WORKER-SANDBOX-INSTALLED*" pkg))))
    (and sym (boundp sym) (symbol-value sym) t)))
(defun pool-run-job (job-id prelude-b64 code-b64)
  (let ((real-out *standard-output*)
        (captured (make-string-output-stream))
        (ok nil) (payload "") (bt "") (user-out ""))
    (let ((*standard-output* captured)
          (*error-output* captured)
          (*trace-output* captured)
          (*debug-io* captured)
          (*package* *pool-job-package*))
      (handler-case
          (let ((prelude (pool-decode-text prelude-b64))
                (code (pool-decode-text code-b64)))
            (if (or (null prelude) (null code))
                (setf ok nil payload "base64 decode failed" bt "")
                (multiple-value-bind (pre-ok pre-payload pre-bt)
                    (evo.worker:run-test-thunk
                     (lambda ()
                       (unless (string= prelude "") (pool-eval-all prelude))
                       nil))
                  (if pre-ok
                      (multiple-value-bind (ok2 payload2 bt2)
                          (evo.worker:run-test-thunk
                           (lambda () (pool-eval-all code)))
                        (setf ok ok2 payload payload2 bt bt2))
                      (setf ok nil
                            payload (concatenate 'string "prelude error: "
                                                 pre-payload)
                            bt pre-bt)))))
        (serious-condition (c)
          (setf ok nil payload (princ-to-string c) bt (pool-backtrace))))
      (setf user-out (get-output-stream-string captured)))
    (format real-out "RESULT ~A {\\"ok\\": ~A, \\"stdout\\": \\"~A\\", \\"return_value\\": \\"~A\\", \\"error\\": \\"~A\\", \\"backtrace\\": \\"~A\\", \\"generation\\": \\"~A\\"}~%"
            job-id
            (if ok "true" "false")
            (pool-json-escape user-out)
            (pool-json-escape (if ok payload ""))
            (pool-json-escape (if ok "" payload))
            (pool-json-escape bt)
            (pool-json-escape *pool-generation*))
    (finish-output real-out)))
(defun pool-split-job (line)
  "Split a JOB line into (job-id prelude-b64 code-b64), or NIL."
  (let ((parts (loop for start = 4 then (+ space 1)
                     for space = (position #\\Space line :start start)
                     collect (subseq line start (or space (length line)))
                     while space)))
    (when (= (length parts) 3) parts)))
(defun pool-handle-line (line)
  (cond ((string= line "")
         ;; Silent no-op: the driver sends one wakeup newline to unstick
         ;; Windows SBCL boot (see _spawn); it must produce no reply.
         nil)
        ((string= line "PING")
         (format t "PONG ~A~%" *pool-worker-id*)
         (finish-output))
        ((string= line "BYE")
         (finish-output)
         (sb-ext:exit :code 0))
        ((string= line "RESET")
         (handler-case
             (progn (when (find-package :graygoo-job)
                      (delete-package :graygoo-job))
                    (pool-fresh-job-package)
                    ;; Package cycled: OK. Sandbox state rides along as
                    ;; info (trusted runs legitimately lack it).
                    (format t "RESET-OK sandbox=~A~%"
                            (if (pool-sandbox-ok-p) "yes" "no")))
           (serious-condition (c)
             (format t "RESET-FAIL ~A~%" (pool-oneline (princ-to-string c)))))
         (finish-output))
        ((and (>= (length line) 4) (string= line "JOB " :end1 4))
         (let ((parts (pool-split-job line)))
           (if parts
               (pool-run-job (first parts) (second parts) (third parts))
               (progn (format t "RESULT - {\\"ok\\": false, \\"error\\": \\"malformed JOB line\\"}~%")
                      (finish-output)))))
        (t (format t "RESULT - {\\"ok\\": false, \\"error\\": \\"unknown command\\"}~%")
           (finish-output))))
(defun pool-main ()
  (handler-case
      (unless (string= *pool-prelude* "")
        (pool-eval-all *pool-prelude*))
    (serious-condition (c)
      (format t "BOOT-FAIL ~A~%" (pool-oneline (princ-to-string c)))
      (finish-output)
      (sb-ext:exit :code 1)))
  (format t "READY ~A~%" *pool-worker-id*)
  (finish-output)
  (loop for line = (ignore-errors (read-line *standard-input* nil nil))
        while line
        do (pool-handle-line line))
  (finish-output)
  (sb-ext:exit :code 0))
(pool-main)
"""


def _lisp_escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _build_script(prelude, generation, worker_id):
    root = ROOT.replace("\\", "/")
    script = _WORKER_SCRIPT
    script = script.replace("@@GENERATION@@", _lisp_escape(generation))
    script = script.replace("@@WORKERID@@", _lisp_escape(worker_id))
    script = script.replace("@@PRELUDE@@", _lisp_escape(prelude))
    script = script.replace("@@ROOT@@", root)
    return script


def _scrub_env(env=None):
    """Copy the process env minus secret-bearing variables.

    The worker keeps everything it needs (PATH, SYSTEMROOT,
    LOCALAPPDATA, TEMP, GRAYGOO_SBCL, ...); only the denylist in
    :data:`_SCRUB_ENV_VARS` is removed so a hostile candidate cannot
    read live keys out of its own OS environment.
    """
    cleaned = dict(os.environ if env is None else env)
    for name in _SCRUB_ENV_VARS:
        cleaned.pop(name, None)
    return cleaned


def _encode_text(text):
    """Base64-encode TEXT (UTF-8) for one-line transport; "" -> "-"."""
    if not isinstance(text, str):
        raise TypeError("code/prelude must be str, got %s"
                        % type(text).__name__)
    if text == "":
        return "-"
    return base64.b64encode(text.encode("utf-8")).decode("ascii")


def _default_generation():
    if _fingerprint is not None:
        try:
            return _fingerprint.compute_string()
        except Exception:
            pass
    return "generation-unknown"


def _sandbox_prelude(sandbox, jail):
    if not sandbox or _sandbox is None:
        return ""
    return _sandbox.build_prelude(jail)


def _jail_root(jail):
    if jail is None:
        return None
    root = jail.root if hasattr(jail, "root") else os.fspath(jail)
    if not isinstance(root, str):
        raise TypeError("jail root must be str, got %s"
                        % type(root).__name__)
    os.makedirs(root, exist_ok=True)
    return root


def _parse_result_line(line, job_id):
    """Parse one ``RESULT <id> <json>`` line; raise WorkerPoisonedError."""
    if not line.startswith("RESULT "):
        raise WorkerPoisonedError("expected RESULT line, got %r"
                                  % line[:120])
    _, _, rest = line.partition(" ")
    echoed, _, payload = rest.partition(" ")
    if not echoed or not payload:
        raise WorkerPoisonedError("malformed RESULT line: %r"
                                  % line[:120])
    if echoed != job_id:
        raise WorkerPoisonedError(
            "job id desync: sent %r, worker answered %r"
            % (job_id, echoed))
    try:
        decoded = json.loads(payload)
    except ValueError as exc:
        raise WorkerPoisonedError("malformed RESULT json: %s" % exc)
    if not isinstance(decoded, dict):
        raise WorkerPoisonedError("RESULT payload is not an object")
    return decoded


# ---------------------------------------------------------------------------
# PersistentWorker: one long-lived SBCL subprocess
# ---------------------------------------------------------------------------

class PersistentWorker:
    """One long-lived SBCL worker driven over stdio (see module docs).

    The reader thread owns ``proc.stdout``; :meth:`run` pairs one ``JOB``
    line with its ``RESULT`` under a lock, so a worker serves one job at
    a time. Timeouts, EOF, and malformed lines poison the worker: it is
    destroyed and must be replaced (see :class:`Pool`).
    """

    def __init__(self, *, sbcl_exe=None, memory_mb=512, prelude="",
                 generation=None, jail_root=None, ready_timeout_s=60.0,
                 executable=None):
        self.worker_id = uuid.uuid4().hex[:12]
        self.generation = (
            _default_generation() if generation is None else generation
        )
        self.jobs_completed = 0
        self.born_at = time.time()
        self.last_used = self.born_at
        self._lock = threading.Lock()
        self._alive = False
        self._proc = None
        self._lines = queue.Queue()
        self._stderr_tail = collections.deque(maxlen=50)
        self._script_path = None
        self._spawn(sbcl_exe=sbcl_exe, memory_mb=memory_mb,
                    prelude=prelude, jail_root=jail_root,
                    ready_timeout_s=ready_timeout_s,
                    executable=executable)

    # -- lifecycle ---------------------------------------------------

    def _spawn(self, *, sbcl_exe, memory_mb, prelude, jail_root,
               ready_timeout_s, executable):
        exe = executable or sbcl_exe
        if exe is None:
            if _workers is not None:
                exe = _workers.resolve_sbcl()
            else:
                exe = os.environ.get("GRAYGOO_SBCL") or ""
        if not exe or not os.path.exists(exe):
            raise WorkerSpawnError(
                "sbcl executable not found: %r" % (exe,))
        memory_mb = int(memory_mb)
        if memory_mb <= 0:
            raise ValueError("memory_mb must be positive, got %r"
                             % (memory_mb,))
        script = _build_script(prelude, self.generation, self.worker_id)
        fd, path = tempfile.mkstemp(suffix=".lisp",
                                    prefix="graygoo-pool-worker-")
        try:
            with os.fdopen(fd, "w", encoding="utf-8",
                           newline="\n") as handle:
                handle.write(script)
        except BaseException:
            try:
                os.unlink(path)
            except OSError:
                pass
            raise
        self._script_path = path
        argv = [exe, "--dynamic-space-size", str(memory_mb),
               "--non-interactive", "--no-userinit", "--no-sysinit",
               "--disable-debugger", "--load", path]
        try:
            proc = subprocess.Popen(
                argv,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                cwd=jail_root or None,
                env=_scrub_env(),
            )
        except OSError as exc:
            self._remove_script()
            raise WorkerSpawnError("failed to spawn sbcl: %s" % exc)
        self._proc = proc
        self._reader = threading.Thread(
            target=self._read_loop, name="pool-reader-%s" % self.worker_id,
            daemon=True)
        self._reader.start()
        self._drainer = threading.Thread(
            target=self._drain_stderr,
            name="pool-stderr-%s" % self.worker_id, daemon=True)
        self._drainer.start()
        # Windows SBCL quirk (verified 2.6.9): the runtime hangs after
        # its banner while stdin is an open pipe with no data and no
        # EOF — --load never runs. One wakeup newline unblocks boot;
        # the worker loop treats the resulting empty line as a silent
        # no-op, so the protocol stays in sync.
        try:
            self._proc.stdin.write(b"\n")
            self._proc.stdin.flush()
        except (OSError, ValueError) as exc:
            self._teardown()
            raise WorkerSpawnError(
                "worker %s stdin broken at boot: %s"
                % (self.worker_id, exc))
        try:
            self._await_ready(ready_timeout_s)
        except BaseException:
            self._teardown()
            raise
        self._alive = True

    def _remove_script(self):
        path, self._script_path = self._script_path, None
        if path:
            try:
                os.unlink(path)
            except OSError:
                pass

    def _read_loop(self):
        stream = self._proc.stdout
        try:
            while True:
                raw = stream.readline()
                if not raw:
                    self._lines.put(_EOF)
                    return
                try:
                    text = raw.decode("ascii", errors="strict")
                except UnicodeDecodeError:
                    text = raw.decode("utf-8", errors="replace")
                if len(text) > MAX_LINE_CHARS + 1:
                    self._lines.put(_EOF)
                    return
                self._lines.put(text.rstrip("\r\n"))
        except (OSError, ValueError):
            self._lines.put(_EOF)

    def _drain_stderr(self):
        stream = self._proc.stderr
        try:
            while True:
                raw = stream.readline()
                if not raw:
                    return
                self._stderr_tail.append(
                    raw.decode("utf-8", errors="replace").rstrip())
        except (OSError, ValueError):
            return

    def _await_ready(self, timeout_s):
        deadline = time.time() + timeout_s
        while True:
            remaining = deadline - time.time()
            if remaining <= 0:
                raise WorkerSpawnError(
                    "worker %s never printed READY" % self.worker_id)
            try:
                line = self._lines.get(timeout=remaining)
            except queue.Empty:
                raise WorkerSpawnError(
                    "worker %s never printed READY" % self.worker_id)
            if line is _EOF:
                raise WorkerSpawnError(
                    "worker %s exited during boot; stderr: %s"
                    % (self.worker_id,
                       " | ".join(self._stderr_tail) or "(empty)"))
            if line == "READY %s" % self.worker_id:
                return
            if line.startswith("BOOT-FAIL"):
                raise WorkerSpawnError("worker %s boot failed: %s"
                                       % (self.worker_id, line))
            # Anything else before READY is startup noise; skip it.

    @property
    def alive(self):
        """True when the child process is believed running."""
        return bool(self._alive and self._proc is not None
                    and self._proc.poll() is None)

    @property
    def age_s(self):
        """Seconds since this worker was spawned."""
        return time.time() - self.born_at

    @property
    def idle_s(self):
        """Seconds since this worker last completed a job."""
        return time.time() - self.last_used

    def _send(self, line):
        try:
            self._proc.stdin.write((line + "\n").encode("ascii"))
            self._proc.stdin.flush()
        except (OSError, ValueError) as exc:
            raise WorkerPoisonedError(
                "worker %s pipe broken: %s" % (self.worker_id, exc))

    def _recv(self, timeout_s):
        try:
            line = self._lines.get(timeout=timeout_s)
        except queue.Empty:
            raise WorkerPoisonedError(
                "worker %s produced no reply within %ss"
                % (self.worker_id, timeout_s))
        if line is _EOF:
            raise WorkerPoisonedError(
                "worker %s hit EOF; stderr: %s"
                % (self.worker_id, " | ".join(self._stderr_tail)
                   or "(empty)"))
        return line

    # -- protocol ----------------------------------------------------

    def run(self, code, *, prelude="", timeout_s=30.0):
        """Run CODE (plus optional PRELUDE) on this worker.

        Returns the :func:`workers.run_lisp` envelope plus
        ``worker_id``/``job_id``/``pooled``/``generation_ok``. Raises
        :class:`WorkerPoisonedError` when the worker desyncs — including
        on wall-clock timeout, because a wedged eval cannot be
        interrupted over stdio. The caller must destroy and replace the
        worker (see :class:`Pool`, which converts timeouts into
        ``timed_out`` envelopes).
        """
        job_id = uuid.uuid4().hex[:12]
        payload = "JOB %s %s %s" % (job_id, _encode_text(prelude),
                                    _encode_text(code))
        started = time.perf_counter()
        with self._lock:
            self._send(payload)
            line = self._recv(timeout_s)
            decoded = _parse_result_line(line, job_id)
        elapsed_ms = round((time.perf_counter() - started) * 1000.0, 1)
        self.jobs_completed += 1
        self.last_used = time.time()
        ok = bool(decoded.get("ok", False))
        error = "" if ok else str(decoded.get("error", ""))
        backtrace = str(decoded.get("backtrace", ""))
        if not ok and backtrace:
            error = (error + "\n--- backtrace ---\n" + backtrace) \
                if error else backtrace
        generation_ok = decoded.get("generation") == self.generation
        return {
            "ok": ok and generation_ok,
            "stdout": str(decoded.get("stdout", "")),
            "return_value": str(decoded.get("return_value", ""))
            if ok else "",
            "error": error if generation_ok else (
                "generation mismatch: worker ran %r, pool owns %r"
                % (decoded.get("generation"), self.generation)),
            "timed_out": False,
            "elapsed_ms": elapsed_ms,
            "worker_id": self.worker_id,
            "job_id": job_id,
            "pooled": True,
            "generation_ok": generation_ok,
        }

    def ping(self, timeout_s=10.0):
        """True when the worker answers PING (proves the loop is live)."""
        with self._lock:
            try:
                self._send("PING")
                line = self._recv(timeout_s)
            except WorkerPoisonedError:
                return False
        return line == "PONG %s" % self.worker_id

    def reset(self, timeout_s=15.0):
        """Soft-reset the worker; True on RESET-OK.

        Deletes and recreates the per-job package. Best effort by
        design (see module docs); hard recycle stays the real hygiene.
        """
        with self._lock:
            try:
                self._send("RESET")
                line = self._recv(timeout_s)
            except WorkerPoisonedError:
                return False
        return line == "RESET-OK" or line.startswith("RESET-OK ")

    def health(self):
        """Health snapshot: liveness, ping, age, job count."""
        alive = self.alive
        return {
            "worker_id": self.worker_id,
            "alive": alive,
            "ping_ok": self.ping(timeout_s=5.0) if alive else False,
            "jobs_completed": self.jobs_completed,
            "age_s": round(self.age_s, 1),
            "idle_s": round(self.idle_s, 1),
        }

    # -- teardown ----------------------------------------------------

    def _teardown(self):
        self._alive = False
        proc, self._proc = self._proc, None
        if proc is not None:
            try:
                proc.stdin.close()
            except (OSError, ValueError):
                pass
            try:
                proc.terminate()
            except (OSError, ValueError):
                pass
            try:
                proc.wait(timeout=5)
            except (subprocess.TimeoutExpired, OSError, ValueError):
                try:
                    proc.kill()
                except (OSError, ValueError):
                    pass
                try:
                    proc.wait(timeout=5)
                except Exception:
                    pass
            for stream in (proc.stdout, proc.stderr):
                try:
                    stream.close()
                except (OSError, ValueError):
                    pass
        self._remove_script()

    def close(self):
        """Polite shutdown: BYE, wait, then teardown. Never raises."""
        try:
            with self._lock:
                try:
                    self._send("BYE")
                except WorkerPoisonedError:
                    pass
                else:
                    try:
                        self._proc.wait(timeout=5)
                    except Exception:
                        pass
        finally:
            try:
                self._teardown()
            except Exception:
                pass

    def __enter__(self):
        return self

    def __exit__(self, _exc_type, _exc, _tb):
        self.close()
        return False


# ---------------------------------------------------------------------------
# Pool: checked-out fleet of persistent workers
# ---------------------------------------------------------------------------

class Pool:
    """Prewarmed fleet of :class:`PersistentWorker` subprocesses.

    :meth:`run` checks out one worker per job (blocking when all are
    busy), health-checks it, runs the job, then recycles or returns it.
    Poisoned workers are destroyed and replaced; when no persistent
    worker can serve and ``oneshot_fallback`` is true, the job is
    delegated to :func:`workers.run_lisp` (call-only; never edited).
    """

    def __init__(self, size=2, *, generation=None, epoch_id="",
                 max_jobs_per_worker=DEFAULT_MAX_JOBS_PER_WORKER,
                 max_age_s=DEFAULT_MAX_AGE_S,
                 reset_every_jobs=0, health_every_jobs=10,
                 health_idle_s=30.0, job_timeout_s=30.0, memory_mb=512,
                 sbcl_exe=None, sandbox=True, jail=None,
                 oneshot_fallback=True, ready_timeout_s=60.0):
        if size is None or int(size) < 1:
            raise ValueError("size must be a positive int, got %r"
                             % (size,))
        if generation is None:
            if _fingerprint is not None:
                try:
                    generation = _fingerprint.compute_string(
                        epoch_id=epoch_id)
                except Exception:
                    generation = "generation-unknown"
            else:
                generation = "generation-unknown"
        self.size = int(size)
        self.generation = generation
        self.max_jobs_per_worker = max_jobs_per_worker
        self.max_age_s = max_age_s
        self.reset_every_jobs = reset_every_jobs
        self.health_every_jobs = health_every_jobs
        self.health_idle_s = health_idle_s
        self.job_timeout_s = job_timeout_s
        self.memory_mb = memory_mb
        self.sbcl_exe = sbcl_exe
        self.sandbox = sandbox
        self.jail = jail
        self.oneshot_fallback = oneshot_fallback
        self.ready_timeout_s = ready_timeout_s
        self._jail_root = _jail_root(jail)
        self._prelude = _sandbox_prelude(sandbox, jail)
        self._idle = collections.deque()
        self._total = 0
        self._lock = threading.Lock()
        self._slots = threading.Semaphore(self.size)
        self._shutdown = False
        #: Fleet counters; mutated under ``self._lock``.
        self.stats = {"spawned": 0, "recycled": 0, "poisoned": 0,
                      "health_failed": 0, "resets": 0, "jobs": 0,
                      "oneshot_fallbacks": 0, "timeouts": 0}
        cold_ms, all_ok = self._prewarm()
        #: Cold-start evidence from construction-time prewarming. A
        #: failed prewarm does not raise; jobs report their own errors
        #: (or fall back to one-shots).
        self.prewarm_evidence = {
            "cold_ms": cold_ms,
            "slots": self.size,
            "all_ok": all_ok,
            "spawned": self._total,
        }

    # -- fleet management --------------------------------------------

    def _spawn_one(self):
        worker = PersistentWorker(
            sbcl_exe=self.sbcl_exe, memory_mb=self.memory_mb,
            prelude=self._prelude, generation=self.generation,
            jail_root=self._jail_root,
            ready_timeout_s=self.ready_timeout_s)
        with self._lock:
            self._total += 1
            self.stats["spawned"] += 1
        return worker

    def _destroy(self, worker, reason):
        try:
            worker.close()
        finally:
            with self._lock:
                self._total -= 1
                if reason in self.stats:
                    self.stats[reason] += 1

    def _prewarm(self):
        started = time.perf_counter()
        all_ok = True
        for _ in range(self.size):
            try:
                self._idle.append(self._spawn_one())
            except (WorkerSpawnError, WorkerError, OSError, ValueError):
                all_ok = False
        cold_ms = round((time.perf_counter() - started) * 1000.0, 1)
        return cold_ms, all_ok

    def _checkout(self):
        """Take one healthy worker (blocking on slots). May raise."""
        self._slots.acquire()
        try:
            with self._lock:
                if self._shutdown:
                    raise RuntimeError("Pool is shut down")
                worker = self._idle.popleft() if self._idle else None
            if worker is None:
                return self._spawn_one()
            if self._needs_health(worker):
                if not self._healthy(worker):
                    with self._lock:
                        self.stats["health_failed"] += 1
                    self._destroy(worker, "poisoned")
                    return self._spawn_one()
            return worker
        except BaseException:
            self._slots.release()
            raise

    def _checkin(self, worker, retire):
        try:
            if retire or self._expired(worker):
                self._destroy(worker, "recycled")
                self._replace_eagerly()
            else:
                with self._lock:
                    self._idle.append(worker)
        finally:
            self._slots.release()

    def _replace_eagerly(self):
        """Best-effort eager replacement to keep the pool warm."""
        try:
            with self._lock:
                if self._shutdown or self._total >= self.size:
                    return
            worker = self._spawn_one()
        except (WorkerSpawnError, WorkerError, OSError, ValueError):
            return
        with self._lock:
            self._idle.append(worker)

    def _needs_health(self, worker):
        if not worker.alive:
            return True
        if (self.health_every_jobs
                and worker.jobs_completed
                and worker.jobs_completed % self.health_every_jobs == 0):
            return True
        return worker.idle_s >= self.health_idle_s

    def _healthy(self, worker):
        if not worker.alive:
            return False
        if worker.generation != self.generation:
            return False
        return worker.ping(timeout_s=5.0)

    def _expired(self, worker):
        if (self.max_jobs_per_worker
                and worker.jobs_completed >= self.max_jobs_per_worker):
            return True
        return bool(self.max_age_s and worker.age_s >= self.max_age_s)

    # -- jobs ----------------------------------------------------------

    def _oneshot(self, code, prelude, timeout_s, note):
        """Delegate one job to workers.run_lisp (fallback path)."""
        if _workers is None:
            raise WorkerError(
                "no persistent worker available (%s) and workers.py "
                "is not importable" % note)
        with self._lock:
            self.stats["oneshot_fallbacks"] += 1
        started = time.perf_counter()
        result = _workers.run_lisp(
            code, timeout_s=timeout_s, memory_mb=self.memory_mb,
            prelude=prelude, sbcl_exe=self.sbcl_exe,
            sandbox=self.sandbox, jail=self.jail)
        result = dict(result)
        result["worker_id"] = "oneshot"
        result["job_id"] = uuid.uuid4().hex[:12]
        result["pooled"] = False
        result["generation_ok"] = True
        result["elapsed_ms"] = round(
            (time.perf_counter() - started) * 1000.0, 1)
        return result

    def run(self, code, *, prelude="", timeout_s=None):
        """Run CODE on the pool; the :func:`workers.run_lisp` envelope
        plus ``worker_id``/``job_id``/``pooled``/``generation_ok``.

        Poisoned workers are destroyed and replaced; timeouts return a
        ``timed_out`` envelope (the wedged worker is always killed).
        When no persistent worker can serve and ``oneshot_fallback``
        is true, the job runs once via :func:`workers.run_lisp`.
        Raises RuntimeError after :meth:`shutdown`.
        """
        if not isinstance(code, str):
            raise TypeError("code must be str, got %s"
                            % type(code).__name__)
        if not isinstance(prelude, str):
            raise TypeError("prelude must be str, got %s"
                            % type(prelude).__name__)
        timeout_s = self.job_timeout_s if timeout_s is None else timeout_s
        if timeout_s is None or timeout_s <= 0:
            raise ValueError("timeout_s must be positive, got %r"
                             % (timeout_s,))
        started = time.perf_counter()
        try:
            worker = self._checkout()
        except (WorkerSpawnError, WorkerError, OSError) as exc:
            if self.oneshot_fallback:
                return self._oneshot(code, prelude, timeout_s,
                                     "checkout failed: %s" % exc)
            raise
        retire = True
        destroyed = False
        try:
            try:
                result = worker.run(code, prelude=prelude,
                                    timeout_s=timeout_s)
            except WorkerPoisonedError as exc:
                self._destroy(worker, "poisoned")
                destroyed = True
                self._replace_eagerly()
                if "no reply within" in str(exc):
                    with self._lock:
                        self.stats["timeouts"] += 1
                    if self.oneshot_fallback:
                        return self._oneshot(
                            code, prelude, timeout_s,
                            "persistent worker timed out")
                    return {
                        "ok": False, "stdout": "", "return_value": "",
                        "error": "wall-clock timeout after %gs; "
                        "worker killed and recycled" % timeout_s,
                        "timed_out": True,
                        "elapsed_ms": round(
                            (time.perf_counter() - started) * 1000.0, 1),
                        "worker_id": worker.worker_id,
                        "job_id": uuid.uuid4().hex[:12],
                        "pooled": True,
                        "generation_ok": True,
                    }
                if self.oneshot_fallback:
                    return self._oneshot(code, prelude, timeout_s,
                                         "worker poisoned: %s" % exc)
                raise
            with self._lock:
                self.stats["jobs"] += 1
            if not result.get("generation_ok", True):
                self._destroy(worker, "poisoned")
                destroyed = True
                self._replace_eagerly()
                if self.oneshot_fallback:
                    return self._oneshot(code, prelude, timeout_s,
                                         "generation mismatch")
                return result
            if (self.reset_every_jobs
                    and worker.jobs_completed % self.reset_every_jobs
                    == 0):
                if worker.reset():
                    with self._lock:
                        self.stats["resets"] += 1
                    retire = False
                else:
                    self._destroy(worker, "poisoned")
                    destroyed = True
                    self._replace_eagerly()
                    return result
            else:
                retire = False
            return result
        finally:
            if not retire:
                self._checkin(worker, False)
            elif destroyed:
                # Destroy paths above adjusted totals; just free the slot.
                self._slots.release()
            else:
                # Unexpected failure mid-job: retire the suspect worker
                # rather than leaking it back into the fleet.
                self._checkin(worker, True)

    # -- fleet operations ----------------------------------------------

    def reset_all(self, timeout_s=15.0):
        """Soft-reset every idle worker; returns ``(ok, total)``.

        Workers that fail reset are destroyed and eagerly replaced.
        """
        with self._lock:
            idle = list(self._idle)
            self._idle.clear()
        ok = 0
        for worker in idle:
            if worker.reset(timeout_s=timeout_s):
                ok += 1
                with self._lock:
                    self.stats["resets"] += 1
                    self._idle.append(worker)
            else:
                self._destroy(worker, "poisoned")
                self._replace_eagerly()
        return ok, len(idle)

    def regenerate(self, generation):
        """Adopt a new generation: destroy the whole fleet.

        Workers are generation-pinned; after an epoch change the stale
        fleet must go. Idle workers are destroyed now; busy workers are
        retired on checkin (their generation no longer matches).
        """
        if not generation:
            raise ValueError("generation is required")
        with self._lock:
            self.generation = generation
            idle = list(self._idle)
            self._idle.clear()
        for worker in idle:
            self._destroy(worker, "recycled")
        self._replace_eagerly()

    def health(self):
        """Snapshot of fleet health: per-worker plus pool stats."""
        with self._lock:
            idle = list(self._idle)
            stats = dict(self.stats)
            total = self._total
        return {
            "size": self.size,
            "total": total,
            "idle": len(idle),
            "shutdown": self._shutdown,
            "stats": stats,
            "workers": [worker.health() for worker in idle],
        }

    def shutdown(self):
        """Destroy every idle worker. Checked-out workers retire on
        checkin. Never raises."""
        with self._lock:
            if self._shutdown:
                return
            self._shutdown = True
            idle = list(self._idle)
            self._idle.clear()
        for worker in idle:
            try:
                self._destroy(worker, "recycled")
            except Exception:
                pass

    def __enter__(self):
        return self

    def __exit__(self, _exc_type, _exc, _tb):
        self.shutdown()
        return False
